services:
  - type: web
    name: ootaMate
    env: python
    plan: starter
    branch: main
    buildCommand: pip install -r requirements.txt && cd Django/ootaMate && python manage.py migrate && python manage.py collectstatic --no-input
    startCommand: cd Django/ootaMate && gunicorn ootaMate.wsgi --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        sync: false
