services:
  - type: web
    name: ootaMate
    env: python
    plan: starter
    branch: main
    buildCommand: |
      cd Django/ootaMate && 
      pip install -r ../../requirements.txt && 
      python manage.py migrate && 
      python manage.py collectstatic --no-input
    startCommand: |
      cd Django/ootaMate && 
      gunicorn ootaMate.wsgi --log-file -
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SECRET_KEY
        sync: false
